In [ ]:
import numpy as np
import matplotlib.pyplot as plt
# Build a vector of 10000 normal deviates with variance 0.5^2 and mean 2
mu, sigma = 2, 0.5
v = np.random.normal(mu,sigma,10000)
# Plot a normalized histogram with 50 bins
plt.hist(v, bins=50, normed=1)       # matplotlib version (plot)
plt.show()

In [ ]:
# Compute the histogram with numpy and then plot it
(n, bins) = np.histogram(v, bins=50, normed=True)  # NumPy version (no plot)
plt.plot(.5*(bins[1:]+bins[:-1]), n)
plt.show()

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x)
print(y)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print(type(a))
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(type(row_r1))
print(type(row_r2))
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                            #          [ 6]
                            #          [10]] (3, 1)"

In [ ]:
import numpy as np

a = np.arange(150).reshape((10, 5, 3))
b = np.arange(150).reshape((10, 5, 3))
print(a)
print('---')
print(b)
print('---')
c = a + b
print(c)
print('---')
print(a[:,:,0].flatten())


In [ ]:
import numpy as np

a = np.arange(27).reshape((3, 3, 3))
b = np.arange(27).reshape((3, 3, 3))
print(a)
print('---')
c = np.dot(a, b)
print(c)
print('---')
print(a[:,:].flatten())

In [ ]:
import numpy as np

input_dim = 2
hidden_dim = 16

synapse_0_1 = (input_dim, hidden_dim); print("------"); print(synapse_0_1)
synapse_0_2 = np.random.random(synapse_0_1); print("------"); print(synapse_0_2)
synapse_0 = 2 * synapse_0_2 - 1; print("------"); print(synapse_0)


In [ ]:
import numpy as np

a1 = np.array([[1,2],[3,4],[5,6]])
print(a1)
print(a1.T)
print(a1.)


In [ ]:

import numpy as np
import tensorflow as tf

def my_func(arg1):
  arg1 = tf.convert_to_tensor(arg1, dtype=tf.float32)
  return tf.matmul(arg1, arg1) + arg1

# The following calls are equivalent.
value_1 = my_func(tf.constant([[1.0, 2.0], [3.0, 4.0]]))
value_2 = my_func([[1.0, 2.0], [3.0, 4.0]])
value_3 = my_func(np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32))

sess = tf.Session()

init = tf.global_variables_initializer()

a = tf.constant(2.0, name='a')
b = tf.constant(3.0, name='b')
c = tf.multiply(a, b, name='c')

b1=tf.constant_initializer(0)

print(a)
print(b1)

tf.summary.scalar('c',c)

merged_summary_op = tf.summary.merge_all()
summary_writer = tf.summary.FileWriter('/tmp/mnist_logs', sess.graph)
    
# # Using the `close()` method.
# sess.run([value_1, value_2, value_3])

sess.run(init)
summary_str = sess.run(merged_summary_op)
print(summary_str)
summary_writer.add_summary(summary_str)

summary_str = sess.run([value_1, value_2, value_3])
print(summary_str)
# summary_writer.add_summary(summary_str)
    
# sess.close()

# print(value_1)
# print(value_2)
# print(value_3)


In [20]:
import numpy as np

# compute sigmoid nonlinearity
def sigmoid(x): #激活函数
    output = 1/(1+np.exp(-x))
    return output

# convert output of sigmoid function to its derivative
def sigmoid_output_to_derivative(output):#激活函数的导数
    return output*(1-output)

print(' ')
print(' - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ')
print(' np.random.random((input_dim, hidden_dim)) - 1 :')

alpha = 0.1  # 学习速率
input_dim = 2  # 因为我们是做两个数相加，每次会喂给神经网络两个bit，所以输入的维度是2
hidden_dim = 16  # 隐藏层的神经元节点数，远比理论值要大（译者注：理论上而言，应该一个节点就可以记住有无进位了，但我试了发现4的时候都没法收敛），你可以自己调整这个数，看看调大了是容易更快地收敛还是更慢
output_dim = 1  # 我们的输出是一个数，所以维度为1

synapse_0 = 2 * np.random.random((input_dim, hidden_dim)) - 1  # 输入层到隐藏层的转化矩阵，维度为2*16， 2是输入维度，16是隐藏层维度
print(synapse_0)
synapse_1 = 2*np.random.random((hidden_dim,output_dim)) - 1
synapse_h = 2*np.random.random((hidden_dim,hidden_dim)) - 1
# 译者注：np.random.random产生的是[0,1)的随机数，2 * [0, 1) - 1 => [-1, 1)，
# 是为了有正有负更快地收敛，这涉及到如何初始化参数的问题，通常来说都是靠“经验”或者说“启发式规则”，说得直白一点就是“蒙的”！机器学习里面，超参数的选择，大部分都是这种情况，哈哈。。。
# 我自己试了一下用【0, 2)之间的随机数，貌似不能收敛，用[0,1)就可以，呵呵。。。

# 以下三个分别对应三个矩阵的变化
synapse_0_update = np.zeros_like(synapse_0)
synapse_1_update = np.zeros_like(synapse_1)
synapse_h_update = np.zeros_like(synapse_h)

print(' ')
print(' - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ')
print(' np.unpackbits(np.array([range(largest_number)], dtype=np.uint8).T, axis=1) : ')

# training dataset generation
int2binary = {}  # 整数到其二进制表示的映射
binary_dim = 8  # 暂时制作256以内的加法， 可以调大

## 以下5行代码计算0-256的二进制表示
largest_number = pow(2, binary_dim)
binary = np.unpackbits(np.array([range(largest_number)], dtype=np.uint8).T, axis=1)

print(binary.shape)
print(binary)
print(binary.T)

print(' ')
print(' - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ')
print(' int2binary : ')

for i in range(largest_number):
    int2binary[i] = binary[i]

print(int2binary)

print(' ')
print(' - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ')
print(' int2binary[13] : ')
print(' np.array([[c[binary_dim - 6 - 1]]]).T : ')

c = int2binary[13]
y = np.array([[c[binary_dim - 6 - 1]]])#正确答案

print(y)
print(y.T)

print(' ')
print(' - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ')
print(' np.dot(X,synapse_0) : ')
print(' sigmoid(t1 + np.dot(layer_1_values[-1],synapse_h)) : ')

j = 11

a_int = np.random.randint(largest_number/2) # int version
a = int2binary[a_int] # binary encoding

b_int = np.random.randint(largest_number/2) # int version
b = int2binary[b_int] # binary encoding

# true answer
c_int = a_int + b_int
c = int2binary[c_int]

# where we'll store our best guess (binary encoded)
# 存储神经网络的预测值
d = np.zeros_like(c)

overallError = 0 #每次把总误差清零

layer_2_deltas = list() #存储每个时间点输出层的误差
layer_1_values = list() #存储每个时间点隐藏层的值
layer_1_values.append(np.zeros(hidden_dim)) #一开始没有隐藏层，所以里面都是0

position = 2

X = np.array([[a[binary_dim - position - 1],b[binary_dim - position - 1]]])
t1 = np.dot(X,synapse_0)
print( t1 )
t3 = layer_1_values[-1]
print( t3 )
t2 = t1 + np.dot(t3,synapse_h)
print( t2 )
layer_1 = sigmoid(t2)
print( layer_1 )

print(' ')
print(' - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ')
print(' ')


 
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
 np.random.random((input_dim, hidden_dim)) - 1 :
[[ 0.67899189  0.11055701  0.62194567 -0.72443175 -0.08671379 -0.74630829
  -0.00465686  0.79242347 -0.74938425 -0.73616943  0.92267072 -0.98155981
  -0.14339554  0.4511752  -0.82348315 -0.95974997]
 [-0.97704169 -0.49402958  0.77128179  0.57444127  0.62660601  0.08398601
   0.93612402  0.73186399  0.98067936  0.95993043  0.14676595  0.06688429
  -0.88384923 -0.6649224   0.50519688 -0.35579916]]
 
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
 np.unpackbits(np.array([range(largest_number)], dtype=np.uint8).T, axis=1) : 
(256, 8)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 1]]
[[0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 ...
 [0 0 0 ... 1 1 1]
 [0 0 1 ... 0 1 1]
 [0 1 0 ... 1 0 1]]
 
 - - - - - - - - - - - - - - - - - - - - - - -

In [ ]:

import numpy as np

x = np.array([[1.,2.],[3.,4.],[5.,6.]])

print(x.T)

In [ ]:
import numpy as np

x = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

print(x.shape)
print(np.dot(x, x))

y = np.array([[[1,2,3],[3,4,5],[1,2,3]],[[1,2,3],[3,4,5],[1,2,3]],[[1,2,3],[3,4,5],[1,2,3]]])

print(y.shape)
print(np.dot(y, y))

In [ ]:

import numpy as np

x = np.full((1,2),2)
y = np.full((2,16),3)
z = np.dot(x, y)
print(z.shape)
print(z)

print(np.arange(11))


In [ ]:

import numpy as np

x = np.random.random((2, 2))
print( x  )
print( np.multiply(x, 2)  )
print( np.exp(x) )

l1 = list()
l1.append(np.ones(10) * 2)
l1.append(np.ones(10) * 3)
l1.append(np.ones(10) * 4)
print(l1)
print(l1[-2])
print(l1[-1])
print(l1[-3])
print(l1[2])
print(l1[1])

In [19]:
import numpy as np

a = np.round(np.random.random((3, 2)) * 10)
b = np.round(a / 2)
c = np.round(np.random.random((2, 3)) * 10)
d = np.arange(1,3)
print( a  )
print( b )
print( c )
print( d ); print( d.shape )
print( ' - ')
print( a - 1 )
# print( a * b ) error : operands could not be broadcast together with shapes (3,2) (2,3) 
print( np.dot(a, c) )
print( np.dot(d, c) )

[[9. 8.]
 [3. 3.]
 [4. 6.]]
[[4. 4.]
 [2. 2.]
 [2. 3.]]
[[1. 2. 2.]
 [9. 4. 2.]]
[1 2]
(2,)
 - 
[[8. 7.]
 [2. 2.]
 [3. 5.]]
[[81. 50. 34.]
 [30. 18. 12.]
 [58. 32. 20.]]
[19. 10.  6.]
