In [5]:

import torch
from    torch import nn
from    torch.nn import functional as F
from    torch import optim

x = torch.rand(100, 16)
layer = torch.nn.BatchNorm1d(16)

print(layer.running_mean, layer.running_var)

out = layer(x)

print(layer.running_mean, layer.running_var)

for parameter in layer.parameters():
    print(parameter)

vars(layer)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0.0498, 0.0543, 0.0509, 0.0496, 0.0456, 0.0523, 0.0509, 0.0536, 0.0540,
        0.0444, 0.0491, 0.0492, 0.0468, 0.0493, 0.0490, 0.0544]) tensor([0.9084, 0.9094, 0.9091, 0.9080, 0.9081, 0.9084, 0.9072, 0.9074, 0.9091,
        0.9087, 0.9079, 0.9082, 0.9085, 0.9087, 0.9080, 0.9088])
Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       requires_grad=True)
Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       requires_grad=True)
