In [2]:
import torch

In [3]:

a = torch.arange(81)
b = a.view([3,3,3,3])
c = a[2:7:]   # 从索引 2 开始到索引 7 停止，间隔为 2
d = b[0:1, 1:2, 0:3] # axis 从 0 开始的, axis=0,axis=1的 0:1 (就是 3 * 3 * 1 * 3)


In [4]:
print(b)

tensor([[[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],

         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]],

         [[18, 19, 20],
          [21, 22, 23],
          [24, 25, 26]]],


        [[[27, 28, 29],
          [30, 31, 32],
          [33, 34, 35]],

         [[36, 37, 38],
          [39, 40, 41],
          [42, 43, 44]],

         [[45, 46, 47],
          [48, 49, 50],
          [51, 52, 53]]],


        [[[54, 55, 56],
          [57, 58, 59],
          [60, 61, 62]],

         [[63, 64, 65],
          [66, 67, 68],
          [69, 70, 71]],

         [[72, 73, 74],
          [75, 76, 77],
          [78, 79, 80]]]])


In [6]:
print(c)

tensor([2, 3, 4, 5, 6])


In [7]:
print(d)

tensor([[[[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]]]])


In [ ]:
# https://pytorch.org/docs/stable/tensors.html

import torch
import numpy as np
from torch.autograd import Variable


a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

print(a[1])

