In [1]:
import numpy as np


hello 3 * 3 * 3

In [2]:
arr1 = np.array([[[1, 2, 3],
                  [1, 2, 3],
                  [4, 2, 3]],
                 
                 [[1, 2, 3], 
                  [5, 2, 3], 
                  [5, 2, 3]],
                 
                 [[1, 2, 3], 
                  [3, 2, 3], 
                  [2, 2, 3]]])

print(arr1.sum(axis=0))


[[ 3  6  9]
 [ 9  6  9]
 [11  6  9]]


hello 4 * 2 * 2


In [3]:
arr2 = np.arange(0, 32)
print(arr2)
arr2 = arr2.reshape(4,2,2,2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]


In [4]:
print(arr2.sum(axis=0))

[[[48 52]
  [56 60]]

 [[64 68]
  [72 76]]]


In [5]:
print(arr2.sum(axis=1))

[[[ 4  6]
  [ 8 10]]

 [[20 22]
  [24 26]]

 [[36 38]
  [40 42]]

 [[52 54]
  [56 58]]]


In [6]:
print(arr2.sum(axis=2))

[[[ 2  4]
  [10 12]]

 [[18 20]
  [26 28]]

 [[34 36]
  [42 44]]

 [[50 52]
  [58 60]]]


In [7]:
print(arr2.sum(axis=3))


[[[ 1  5]
  [ 9 13]]

 [[17 21]
  [25 29]]

 [[33 37]
  [41 45]]

 [[49 53]
  [57 61]]]
