In [2]:
import numpy as np
from numpy import matlib

In [3]:
# arr1 = np.array([1, 2, 3, 4])
# # print(arr1)
#
arr2 = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [8, 9, 10, 11], [2, 5, 6, 8]])
a = np.zeros(6)#创建长度为6的，元素都是0一维数组
a = np.zeros((2,3))#创建2行3列，元素都是0的二维数组
a = np.ones((2,3))#创建2行3列，元素都是1的二维数组
a = np.empty((2,3)) #创建2行3列,未初始化的二维数组
a = np.arange(6)#创建长度为6的，元素都是0一维数组array([0, 1, 2, 3, 4, 5])
a = np.arange(1,7,1)#结果与np.arange(6)一样。第一，二个参数意思是数值从1〜6,不包括7.第三个参数表步长为1.
a = np.linspace(0,10,7) # 生成首位是0，末位是10，含7个数的等差数列[  0.           1.66666667   3.33333333   5.         6.66666667  8.33333333  10.        ]
a = np.logspace(0,4,5)#用于生成首位是10**0，末位是10**4，含5个数的等比数列。
#
# 用一个n行列向量和一个m列行向量构造出一个n×m矩阵
np.array([[1],[2]]) + ([[10,20,30]]) # ([[10,20,30]]) 是生成一个list，注意，不是np.array
# print(arr2)
# print(arr1.dtype)
# print(arr2.dtype)
# print(arr1.size)
# print(arr2.size)
# print(arr1.shape)
# print(arr2.shape)
#
# start:stop:step （stop不提取的）
a = np.arange(81)
b = a.reshape([3,3,3,3])
c = a[2:7:2]   # 从索引 2 开始到索引 7 停止，间隔为 2
d = b[:, :, 0:2] # axis 从 0 开始的, axis=0,axis=1的 0:1 (就是 3 * 3 * 1 * 3)
#
# 连接
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[10,20],[30,40],[50,60]])
np.vstack((a,b))
    # array([[ 1,  2],
    #        [ 3,  4],
    #        [ 5,  6],
    #        [10, 20],
    #        [30, 40],
    #        [50, 60]])
np.hstack((a,b))
    # array([[ 1,  2, 10, 20],
    #        [ 3,  4, 30, 40],
    #        [ 5,  6, 50, 60]])
np.concatenate # 连接沿现有轴的数组序列
np.stack # 沿着新的轴加入一系列数组。
np.hstack # 水平堆叠序列中的数组（列方向）
np.vstack # 竖直堆叠序列中的数组（行方向）
# 分割数组
np.split # 将一个数组分割为多个子数组
np.hsplit # 将一个数组水平分割为多个子数组（按列）
np.vsplit # 将一个数组垂直分割为多个子数组（按行）
#
# 修改元素
arr2[0,0] = 20
#
# transpose	对换数组的维度
a.T # 和 a.transpose() 相同
np.rollaxis # 向后滚动指定的轴
np.swapaxes # 对换数组的两个轴
# # 维度
# print(arr1.ndim)
# print(arr2.ndim)
# print(arr2)
#
# 更改维度
arr2.shape = 2, 2, 2, 2, 2
# print(arr2)
# print(arr2.ndim)
#
# # 秩为2的ndarray，添加一列; 当然也可添加两列 q = np.append(Y,[[9,99],[10,100]], axis=1)
print(np.append(np.array([[1,2,3],[4,5,6]]),[[9],[10]], axis=1)) 

# 向秩为2的ndarray第二行前，插入4,5,6,7
print(np.insert(arr2,1,[4,5,6,7],axis=0)) 

# # 删除第一列和第三列(最后一列)的元素
print(np.delete(np.array([[1,2,3],[4,5,6],[7,8,9]]), [0,2], axis=1)) 

In [4]:
# ############################第二中方法##########################
# 左闭右开
# print(np.arange(0, 1, 0.001))

# 等差数列
# 起始值，终值，元素个数
# print(np.linspace(1, 12, 12))

# 等比
# 起始值，终值，元素个数
# print(np.logspace(0, 2, 20))

# zeros全0矩阵
# print(np.zeros((2, 3)))

# 全1矩阵
# print(np.ones((5, 3)))

# 对角矩阵
# print(np.diag([1, 2, 3, 4]))

# 单位矩阵
# print(np.eye(4))

In [5]:
# 随机数--------------------------------------
# 0-1之间100个随机数
# print(np.random.random(100))

# 10行5列 服从均匀分布
# print(np.random.rand(10, 5))

# 10行5列 服从正太分布
# print(np.random.randn(10, 5))

# 随机整数2行5列  左闭右开
# print(np.random.randint(2, 10, size=[2, 5]))


In [6]:
###############索引访问数组###################
# arr1 = np.arange(10)

# 一维索引
# print(arr1[5])

# 切片 取3-4
# print(arr1[3:5])
# 取前5个
# print(arr1[:5])

# 修改数组元素
# arr1[2:4] = 55, 66
# print(arr1)

# 隔一个取一个
# 取所有行arr[:],步长为2arr[::2]
# print(arr1[::2])

In [7]:
####################二维##################
# arr2 = np.arange(15)
# print(arr2)
# arr2.shape = 3, 5
# print(arr2)

# 取2行 6-7
# print(arr2[1, 1:3])

# 取2 3 行的第3 4 5列(下标从0开始)
# print(arr2[1:3, 2:6])

# 取第1行的第5个  和第3行的第4个
# print(arr2[[0, 2], [4, 3]])
# print(arr2[[(0, 2), (4, 3)]])

# 取第2行的第0 2 3个  和第3行的第0 2 3个
# print(arr2[1:3, [0, 2, 3]])

print()

# 根据bool值  取第3行的值
# mask = np.array([0, 1, 1, 0, 0], dtype=bool)
# print(arr2[2, mask])


In [8]:
######################修改数组的形态###############

# arr = np.arange(12)
# arr1 = arr.reshape(3, 4)
# print(arr1)

# 展平数组 按行展开
# print(arr1.ravel())

# flatten默认按行展开   F按列展开
# print(arr1.flatten())
# print(arr1.flatten('F'))

# 数乘
# arr2 = 3 * arr1
# print(arr2)

# 横向组合
# print(np.hstack((arr1, arr2)))
# print(np.concatenate((arr1, arr2), axis=1))

# 纵向组合
# print(np.vstack((arr1, arr2)))
# print(np.concatenate((arr1, arr2), axis=0))

####数组的分割
# arr = np.arange(16).reshape(4, 4)

# 横向分割(分成左右)分的个数必须能被列数整除
# print(np.hsplit(arr, 2))
# print(np.split(arr, 2, axis=1))

# 纵向分割 （分成上下）
# print(np.vsplit(arr, 2))


In [9]:
#################################矩阵######################
# 创建矩阵
m1 = np.mat('1,1,1;1,2,1;2,1,1')
m = matlib.mat('1,2,3;4,5,6;7,8,9')
# print(m1)
#
m2 = matlib.matrix([[1, 2, 3], [0, 1, 3], [2, 1, 2]])
# print(m2)

arr1 = np.eye(3)
# arr2 = 3 * arr1

# 矩阵组合
# m3 = matlib.bmat('arr1 arr2;arr2 arr1')
# print(m3)

# 矩阵相加
# print(m1 + m2)

# 相乘
# print(m1 * m2)

# 矩阵的按位相乘
# print(matlib.multiply(m1, m2))

# 矩阵转置
# print(m1.T)

# 矩阵的逆
# print(m1.I)


In [10]:
#########################数组的运算#############################
# 常见的函数有 四则运算、比较运算、逻辑运算
x1 = np.array([1, 2, 3])
x2 = np.array([4, 2, 6])

# print(x1 + x2)
# print(x1 - x2)
# print(x1 * x2)
# print(x1 / x2)

# 幂运算
# print(np.power(x1, x2))

# 逻辑运算
# all表示and  any表示or
# print(np.all(x1 == x2))
# print(np.any(x1 == x2))

# 广播机制
a1 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
a2 = np.array([1, 2, 3])
# print(a1.ndim)
# print(a1 + a2)

######读取文件
# 保存.npy文件
# np.save('a1', a1)
##### 保存多个数组
# np.savez('a2z', a1, a2)
##### 读取
# print(np.load('a1.npy'))

##### 读取多个数组的保存文件
# print(np.load('a2z.npz'))
# data = np.load('a2z.npz')
# print(data['arr_0'])
# print(data['arr_1'])

# 保存txt文件(默认空格分隔)
# np.savetxt('a1.txt', a1, fmt='%d', delimiter=',')
# np.savetxt('a1.txt', a1,fmt='%d')

# 读取txt
# print(np.loadtxt('a1.txt', delimiter=','))

In [11]:
####################使用函数进行简单的统计分析#################
arr4 = np.random.randint(1, 100, size=12)
# print(arr4)
# arr4.shape = 3, 4

# 直接排序
# arr4.sort()
# print(arr4)

# arr4.sort(axis=1)
# print(arr4)
# arr4.sort(axis=0)
# print(arr4)

# 返回重新排序值的下标
# print(arr4.argsort())

In [12]:
###########去重与重复数据#############
# 1数组内数据去重
names = np.array(['小明', '小花', '小花', '小明', '小白', '小花', '小白', '小黄', '小黑'])
# print('去重之后的数据', np.unique(names))
# print(sorted(set(names)))

# 重复数据(使数组内的数据重复两次)  tile对整个数组进行重复
# print(np.tile(names, 2))
# print(arr2)
# 按行重复  repeat对数组元素进行重复
# print(np.repeat(arr2, 2, axis=1))

# 按列重复
# print(np.repeat(arr2, 2, axis=1))

# print(np.tile(arr2, 2))
# print(np.repeat(arr2, 2))

In [13]:
#################3###########常用统计函数
####均为聚合计算
arr5 = np.arange(16).reshape(2, 8)
# print(arr5)

# 求和
# print(np.sum(arr5))

# 纵向求和
# print(np.sum(arr5,axis=0))

# h横向求和
# print(np.sum(arr5,axis=1))

# 平均值
# print(np.mean(arr5))
# print(np.mean(arr5, axis=0))
# print(np.mean(arr5, axis=1))

# 标准差
# print(np.std(arr5))

# 方差
# print(np.var(arr5))

# 最小值
# print(np.min(arr5))

# print(np.min(arr5, axis=1))

In [14]:
####返回最值得索引
# 最小
# print(np.argmin(arr5))
# print(np.argmin(arr5,axis=0))
# print(np.argmin(arr5,axis=1))

# 最大
# print(np.argmax(arr5))

In [15]:
########################################
####非聚合计算####
ar1 = np.array([4, 2, 5, 6, 3, 8, 9, 6, 3, 5, 4, 2])
print(ar1)
# 累积求和
print(np.cumsum(ar1))

# 累积求积
print(np.cumprod(ar1))




[4 2 5 6 3 8 9 6 3 5 4 2]
[ 4  6 11 17 20 28 37 43 46 51 55 57]
[       4        8       40      240      720     5760    51840   311040
   933120  4665600 18662400 37324800]
