In [21]:
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(1, 10)
y = np.linspace(9, 1, 9)
print(x)
print(y)

[1 2 3 4 5 6 7 8 9]
[9. 8. 7. 6. 5. 4. 3. 2. 1.]


In [22]:
x = np.reshape(x, [3, 3])
print(x)
y = np.reshape(y, [3, 3])
print(y)

print(x * y)
print(y * x)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]
[[ 9. 16. 21.]
 [24. 25. 24.]
 [21. 16.  9.]]
[[ 9. 16. 21.]
 [24. 25. 24.]
 [21. 16.  9.]]
